[Interface]
PrivateKey = CLIENT_A_PRIVATE_KEY_BASE64_HERE
ListenPort = 51820
Address = 10.0.8.2/24

[Peer]
PublicKey = SERVER_PUBLIC_KEY_BASE64_HERE
Endpoint = 10.0.0.23:51820
AllowedIPs = 10.0.8.1/32
PersistentKeepAlive = 25
